### ISSUE TITLE
Need to enable "Install Project" on RTD

### ISSUE THREAD

**Issue by jeffwidman** [flask-debugtoolbar/flask-debugtoolbar#109]
Right now, we are manually setting version in `setup.py` and `conf.py` which is annoying. `conf.py` should be updated to use `pkg_resources.get_distribution('Flask-DebugToolbar').version`. 

Unfortunately, when I tried this, it broke ReadTheDocs because they are not first installing the package before building the docs. 

Poking through RTD documentation, it looks like RTD has a "Install Project" option that will force package install before building: http://docs.readthedocs.io/en/latest/builds.html#understanding-what-s-going-on

Unfortunately, I don't have the proper access rights in RTD to do this.

**Comment by mgood** [comment]
@jeffwidman added you as a maintainer on RTD

**Comment by jeffwidman** [comment]
I enabled "Install Project" option in their UI. Looks like their recommended thing is to add a RTD config file. Maybe get to that in the future.
