### ISSUE TITLE
format_sql(query.statement, query.parameters) missed all params

### ISSUE THREAD

**Issue by gshmu** [flask-debugtoolbar/flask-debugtoolbar#134]
https://github.com/mgood/flask-debugtoolbar/blob/d852042ccb68d0507e0ef8d9e0d53287ca766f3b/flask_debugtoolbar/utils.py#L75

**Comment by jeffwidman** [comment]
@gshmu can you explain the problem here a little better? I'm not quite understanding this cryptic issue description...
