### ISSUE TITLE
Review flask.dispatch_request for possible tweaks

### ISSUE THREAD

**Issue by jeffwidman** [flask-debugtoolbar/flask-debugtoolbar#150]
Our `dispatch_request()` was a modified version of `flask.dispatch_request()`, but that fork happened years ago.

Now would be a good time to review how they wire it to see if there are any additional improvements/tweaks that should be pulled in:
https://github.com/pallets/flask/blob/a3e4395a42574386a15ef6ca1afa83ff9787608f/src/flask/app.py#L1907-L1946

**Comment by mattaw** [comment]
Having reviewed the code in flask-debugtoolbar and that in the current version of Flask I can't see any functional difference (except wiring in debugtoolbar process_view). However, in the process of exploring what it was doing I am concerned that the debugtoolbar testing through tox passes just fine if I comment out the monkeypatch completely so I will try to improve that.

**Comment by jeffwidman** [comment]
Sounds great, then let's close this. I opened https://github.com/flask-debugtoolbar/flask-debugtoolbar/issues/151 to track the test improvement.

**Comment by jeffwidman** [comment]
And thanks for looking into this @mattaw!
