### ISSUE TITLE
Flask-SQLAlchemy 3 compatibility

### ISSUE THREAD

**Issue by davidism** [flask-debugtoolbar/flask-debugtoolbar#185]
Flask-SQLAlchemy 3 was just released, here's the changelog: https://flask-sqlalchemy.palletsprojects.com/en/3.0.x/changes/#version-3-0-0

Relevant changes for Flask-DebugToolbar are:

- [ ] `SQLALCHEMY_RECORD_QUERIES` is disabled by default and not enabled automatically with debug mode. You might want to show a warning if it's not enabled when using the debug toolbar.
- [ ] `get_debug_queries` is renamed to `get_recorded_queries`, and moved to `from flask_sqlalchemy.record_queries import get_recorded_queries`.
- [ ] The query info is a dataclass instead of a tuple. The `context` property is renamed to `location`.

The renames/moves currently show deprecation warnings, but will be removed in 3.1.

**Comment by nickjj** [comment]
Thanks a lot for the heads up David.

This would be a great first PR if someone wants to take this on. One thing to consider is we'd like to keep backwards compatibility with SQLAlchemy 2.X for quite some time before dropping it. An ideal solution would work with both.

**Comment by Dosenpfand** [comment]
Hi @nickjj, I openend pull request #186 to address this issue.

**Comment by nickjj** [comment]
#186 has been merged, thanks a lot!
